#!/bin/sh
'''exec' D:/conda3/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from qtawesome.icon_browser import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
